---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0" # Listens to: 0.0.0.0
elasticsearch.hosts: ["http://elasticsearch:9200"]
#elasticsearch.hosts: ["http://localhost:9200"] If using Coordinator inside this container

xpack.monitoring.ui.container.elasticsearch.enabled: true
